version: "3.7"
services:
  app:
    build: .
    image: muhsenmaqsudi/laradvance
    container_name: laradvance_app
    user: "1000:1000"
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      - ./:/srv:delegated
    environment:
      REDIS_HOST: redis
      DB_HOST: db
  db:
    image: mysql:8
    container_name: laradvance_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  server:
    image: nginx:stable
    container_name: laradvance_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/srv
      - ./storage/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - db
  redis:
    container_name: laradvance_redis
    image: redis:alpine
    volumes:
      - redisdata:/data
    restart: always
    ports:
      - "16379:6379"
  worker:
    build:
      context: ./storage/docker/php-worker
    container_name: laradvance_worker
    restart: unless-stopped
    volumes:
      - ./:/srv:delegated
      - ./storage/docker/php-worker/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./storage/docker/php-worker/supervisord.d:/etc/supervisor/conf.d
  websocket:
    image: node:lts
    container_name: laradvance_websocket
    entrypoint: ["yarn", "run", "websocket"]
    restart: unless-stopped
    ports:
      - 6001:6001
    volumes:
      - ./:/srv:z
    working_dir: /srv
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
