version: "3"
services:
  app:
    build: .
    image: muhsenmaqsudi/laradvance
    container_name: laradvance_app
    user: "1000:1000"
    restart: unless-stopped
    volumes:
      - ./:/srv
  db:
    image: mysql:latest
    container_name: laradvance_db
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "4406:3306"
    volumes:
      - dbdata:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    container_name: laradvance_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/srv
      - ./storage/docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - db
  redis:
    container_name: laradvance_redis
    image: redis:latest
    volumes:
      - redisdata:/data
    restart: always
    ports:
      - "7379:6379"
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
